/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaotomasyon;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Load extends javax.swing.JFrame {

  private static final String url = "jdbc:mysql://localhost:3306/kayıt0";
 private static final String user = "root";
 private static final String pass = "";
   
   
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    
    
    
    
    
    public Load() {
        initComponents();
        upDateDB();
    }
    
      //===========================================Function================================================
     public void upDateDB()
    {
        try
        {
           
           Class.forName("com.mysql.jdbc.Driver"); 
            sqlConn = DriverManager.getConnection(url,user,pass);
            pst = sqlConn.prepareStatement("select * from newveri");
            
            rs = pst.executeQuery();
            ResultSetMetaData StData = rs.getMetaData();
            
            q = StData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                
                Vector columnData = new Vector();
                
                for (i = 1; i <= q; i++)
                {
                   columnData.add(rs.getString("id"));
                   columnData.add(rs.getString("aditr"));
                   columnData.add(rs.getString("soyaditr"));
                   columnData.add(rs.getString("teltr"));
                   columnData.add(rs.getString("maastr"));
                   columnData.add(rs.getString("mevkitr"));
                   columnData.add(rs.getString("adrestr"));
                }
                    RecordTable.addRow(columnData);                
                
            }
         
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
        
    }
    
    
  
    //===========================================End Function================================================
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        maasD = new java.awt.TextArea();
        mevkiD = new java.awt.TextArea();
        soyadiD = new java.awt.TextArea();
        adity = new java.awt.TextArea();
        adresD = new java.awt.TextArea();
        telD = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("adi");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, 50));

        jLabel5.setText("Soyad");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 80, 50));

        jLabel3.setText("Adres:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 80, 50));

        jLabel2.setText("Tel:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "İd", "Adi:", "SoyAdi:", "Telefon", "Maaş", "Mevki", "Adres"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 970, 310));

        jButton2.setText("Ekle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 70, 60));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton3.setText("Düzenle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 70, 60));

        jButton4.setText("Sil");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 70, 60));

        jButton5.setText("çık");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, 70, 60));

        jLabel6.setText("Maaş:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 80, 50));

        jLabel7.setText("Mevki");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 80, 50));
        jPanel3.add(maasD, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 220, 50));
        jPanel3.add(mevkiD, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 220, 50));
        jPanel3.add(soyadiD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 220, 50));
        jPanel3.add(adity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 220, 50));
        jPanel3.add(adresD, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 220, 50));
        jPanel3.add(telD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 220, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();

        int SelectedRows = jTable1.getSelectedRow();

        adity.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        soyadiD.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        telD.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        maasD.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        mevkiD.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        adresD.setText(RecordTable.getValueAt(SelectedRows, 6).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try
        {

            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(url,user,pass);
            pst = sqlConn.prepareStatement("insert into newveri(aditr,soyaditr,teltr,mevkitr,"
                + "maastr,adrestr)value(?,?,?,?,?,?)");

            pst.setString(1, adity.getText());
            pst.setString(2, soyadiD.getText());
            pst.setString(3, telD.getText());
            pst.setString(4, mevkiD.getText());
            pst.setString(5, maasD.getText());
            pst.setString(6, adresD.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Kullanıcı Eklendi");
            upDateDB();
        }

        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.
                SEVERE,null, ex);

        } catch (SQLException ex) {
            //System.err.println(ex);
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.
                SEVERE,null, ex);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(url,user,pass);
            int row =jTable1.getSelectedRow();
            String value =(jTable1.getModel().getValueAt(row, 0).toString());
            pst = sqlConn.prepareStatement("update newveri SET aditr=?, soyaditr=?, teltr=?, maastr=?, mevkitr=? , adrestr=? where id ="+value);

            pst.setString(1, adity.getText());
            pst.setString(2, soyadiD.getText());
            pst.setString(3, telD.getText());
            pst.setString(4, maasD.getText());
            pst.setString(5, mevkiD.getText());
            pst.setString(6, adresD.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Düzenlendi!");
            upDateDB();

        }catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.
                SEVERE,null, ex);
            JOptionPane.showMessageDialog(this,"Hata!");

        } catch (SQLException ex) {
            //System.err.println(ex);
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.
                SEVERE,null, ex);
            JOptionPane.showMessageDialog(this,"Hata!");
        }

        /*
        try
        {

            pst = sqlConn.prepareStatement("UPDATE newveri SET aditr = ?, soyadtr = ? "+ "WHERE teltr =?");

            pst.setString(1, adity.getText());
            pst.setString(2, soyadiD.getText());
            pst.setString(3, telD.getText());
            pst.setString(4, mevkiD.getText());
            pst.setString(5, maasD.getText());
            pst.setString(6, adresD.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Kullanıcı Düzenlendi!");
            upDateDB();
        }

        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.
                SEVERE,null, ex);
            JOptionPane.showMessageDialog(this,"Hata!");

        } catch (SQLException ex) {
            //System.err.println(ex);
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.
                SEVERE,null, ex);
            JOptionPane.showMessageDialog(this,"Hata!");
        }

        */
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();

        try
        {
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            deleteItem = JOptionPane.showConfirmDialog(null,"Kullanıcı Silinsin mi ?",
                "Dikkat",JOptionPane.YES_NO_OPTION);
            if (deleteItem ==JOptionPane.YES_OPTION )
            {

                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(url,user,pass);
                pst = sqlConn.prepareStatement("delete from newveri where id =?");

                pst.setInt(1, id);
                pst.executeUpdate();

                upDateDB();

                adity.setText("");
                soyadiD.setText("");
                telD.setText("");
                maasD.setText("");
                mevkiD.setText("");
                adresD.setText("");

            }
        }catch (SQLException ex) {

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Load.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private JFrame frame;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Uygulama Kapatılsın mı? ","MySQL Connector",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
    {
        System.exit(0);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Load().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea adity;
    private java.awt.TextArea adresD;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.TextArea maasD;
    private java.awt.TextArea mevkiD;
    private java.awt.TextArea soyadiD;
    private java.awt.TextArea telD;
    // End of variables declaration//GEN-END:variables
}
