/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaotomasyon;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
     public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        user0 = new javax.swing.JTextField();
        pass10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user0.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        user0.setForeground(new java.awt.Color(102, 102, 102));
        user0.setText("Kullanıcı Adi...");
        user0.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        user0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user0ActionPerformed(evt);
            }
        });
        jPanel2.add(user0, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 270, 40));

        pass10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        pass10.setForeground(new java.awt.Color(102, 102, 102));
        pass10.setText("Şifre...");
        pass10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(pass10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 270, 40));

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setLabel("Giriş");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 280, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 430, 400));

        jPanel1.setBackground(new java.awt.Color(0, 181, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/d57266ab06dc29ec0924e36695d78aee (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 240, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user0ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Connection mycoib;  
   String url = "jdbc:mysql://localhost:3306/kayıt0";
   String user = "root";
   String pass = "";
   
  try{
      Class.forName("com.mysql.jdbc.Driver");
     mycoib = DriverManager.getConnection(url,user,pass);
     Statement stmt = mycoib.createStatement();
   
     String sql = "Select * from user where user='"+user0.getText()+"' and sifre='"+pass10.getText()+"'";
     ResultSet rs=stmt.executeQuery(sql);
     if(rs.next()){
        JOptionPane.showMessageDialog(this,"Başarılı");
         new Load().setVisible(true);
         this.dispose();
         
    }else{
         JOptionPane.showMessageDialog(this,"Başarısız Lütfen Tekrar Giriniz! ");
         mycoib.close();
        
     }
  }catch(SQLException e){
      e.printStackTrace();
      System.out.println("HATA");
  }     catch (ClassNotFoundException ex) {
            Logger.getLogger(otomasyonn.Login.class.getName()).log(Level.SEVERE, null, ex);
        }
  
   

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField pass10;
    private javax.swing.JTextField user0;
    // End of variables declaration//GEN-END:variables
}
